# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-win:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    - name: Build Linux
      run: |
        pyinstaller -F --icon="react.ico" React.py
    - name: Build Windows
      uses: FlawCra/pyinstaller-action-windows@main
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/React,dist/windows/React.exe"
        token: ${{ secrets.GITHUB_TOKEN }}
